spring.application.name=JustEat

server.port = 8090
spring.datasource.url=jdbc:postgresql://localhost:5432/justeat
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=admin
spring.security.user.password=admin